# Sử dụng cho màn hình Guition ESP32 S3 4848S040 4.0 inch
esphome:
  name: guition-webview-local
  friendly_name: Guition WebView Local
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: -100
    then:
      - script.execute: inactivity_timer

      - lambda: |-
          auto url = id(rwv_default_url).state;
          if (url.size() > 0) {
            id(rwv).set_url(url);
          }
external_components:
  - source: 
      type: local
      path: components 
debug:
  update_interval: 2s

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
    components:
      - name: "espressif/esp_websocket_client"
        ref: 1.5.0
      - name: "bitbank2/jpegdec"
        source: https://github.com/strange-v/jpegdec-esphome

remote_webview:
  id: rwv
  server: 192.168.10.2:8081
  url: http://192.168.10.2:8123/dashboard-mobile/2
  full_frame_tile_count: 1
  max_bytes_per_msg: 61440
  jpeg_quality: 40
  rotation: 0


text:
  - platform: template
    id: rwv_default_url
    name: "URL mặc định"
    optimistic: true
    restore_value: true
    mode: TEXT
    min_length: 1

#  - platform: template
  #  id: rwv_url
  #  name: "URL hiển thị"
  #  optimistic: true
 #   restore_value: false
  #  mode: TEXT
  #  min_length: 1
  #  set_action:
   #   - lambda: id(inactivity_timer).execute();
    #  - lambda: |-
     #     if (!id(rwv).open_url(std::string(x.c_str()))) {
            #id(rwv).set_url(std::string(x.c_str()));
      #      ESP_LOGI("remote_webview", "URL queued (not connected): %s", x.c_str());
    #      }


  - platform: template
    id: rwv_url
    name: "URL hiển thị"
    optimistic: true
    restore_value: false
    mode: TEXT
    min_length: 1
    set_action:
      - lambda: id(inactivity_timer).execute();
      - lambda: |-
          std::string base_url = x.c_str();
          std::string url = base_url;          
          if (
            base_url.ends_with(".jpg")  ||
            base_url.ends_with(".jpeg") ||
            base_url.ends_with(".png")  ||
            base_url.ends_with(".webp")
          ) {
            url += "?t=";
            url += to_string(millis());
          }

          if (!id(rwv).open_url(url)) {
            id(rwv).set_url(url);
            ESP_LOGI("remote_webview", "URL queued (not connected): %s", url.c_str());
          } else {
            ESP_LOGI("remote_webview", "URL loaded: %s", url.c_str());
          }

number:
  - platform: template
    name: "Sleep time"
    id: sleep_time
    optimistic: true
    initial_value: 15
    restore_value: yes
    unit_of_measurement: "s"
    device_class: duration
    mode: box
    min_value: 5
    max_value: 600
    step: 1

script:
  - id: inactivity_timer
    mode: restart
    then:
      - if:
          condition:
            light.is_off: back_light
          then:
            - light.turn_on:
                id: back_light
            - delay: 0.5s
            - lambda: |-
                id(rwv).disable_touch(false);
      - delay: !lambda 'return id(sleep_time).state * 1000;'
      - light.turn_off:
          id: back_light
      - lambda: |-
          id(rwv).disable_touch(true);

sensor:
  - platform: debug
    free:
      name: "Heap Free"

    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: Free PSRam
      unit_of_measurement: "MB"
      icon: "mdi:memory"
      accuracy_decimals: 1
      filters:
        - lambda: return x /1048576;
    cpu_frequency:
      name: "CPU Frequency"
      unit_of_measurement: "MHz"
      filters:
        - lambda: return x /1000000;

text_sensor:  

  - platform: wifi_info
    ip_address:
      name: IP
      id: ip_wifi
    mac_address:
      name: MAC ESP
      id: mac_address
    ssid:
      name: WIFI KẾT NỐI
      id: ssid_wifi

button:
  - platform: template
    name: "Go Home"
    id: go_home
    icon: "mdi:home"
    on_press:
      then:
        - lambda: |-
            auto url = id(rwv_default_url).state;
            if (url.size() == 0) {
              ESP_LOGW("remote_webview", "Default URL is empty");
              return;
            }

            if (!id(rwv).open_url(url)) {
              id(rwv).set_url(url);
              ESP_LOGI("remote_webview", "Default URL queued: %s", url.c_str());
            } else {
              ESP_LOGI("remote_webview", "Opened default URL: %s", url.c_str());
            }


  - platform: restart 
    name: "Khởi động lại"
    id: restart_switch  
                  

psram:
  mode: octal
  speed: 80MHz
logger:
  hardware_uart: UART0
api:
ota:
  - platform: esphome
   
wifi:
  id: iptime
  ssid: xxxx
  password: "xxxx"
  manual_ip:
    static_ip: 192.168.x.x
    gateway: 192.168.x.x
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4
  ap:
    ssid: "Guition webview"
    password: "12345678"

captive_portal:   
spi:
  clk_pin: GPIO48
  mosi_pin: GPIO47
i2c:
  - id: bus_a
    sda: GPIO19
    scl: GPIO45
display:
  - platform: st7701s
    show_test_card: False
    update_interval: never
    auto_clear_enabled: False
    spi_mode: MODE3
    data_rate: 40MHz
    color_order: RGB
    invert_colors: False
    dimensions:
      width: 480
      height: 480
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 16MHz
    pclk_inverted: False
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xCD, 0x00]
    data_pins:
      red:
        - GPIO11
        - GPIO12
        - GPIO13
        - GPIO14
        - GPIO0
      green:
        - GPIO8
        - GPIO20
        - GPIO3
        - GPIO46
        - GPIO9
        - GPIO10
      blue:
        - GPIO4
        - GPIO5
        - GPIO6
        - GPIO7
        - GPIO15

touchscreen:
  platform: gt911
  transform:
    mirror_x: false
    mirror_y: false
  on_touch:
    then:
      - script.execute: inactivity_timer

output:
  - platform: ledc
    pin: GPIO38
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
    on_turn_off:
      then:
        - button.press: go_home


